### ISSUE TITLE
Wordpress generator: "throw er; // Unhandled 'error' event"

### ISSUE THREAD

**Issue by johnbburg** [forumone/generator-web-starter#106]
After a fresh update of generator-web-starter, and trying to set up a wordpress project, I get the below output. I believe the error is referencing this line: https://github.com/forumone/generator-web-starter-wordpress/blob/master/web-starter/templates/config/shell/custom/post-provision.unprivileged.sh#L9. 

``` <%= services.web.doc_root %> ``` Seems to be the way this value is accessed in several places.

```
$ yo web-starter
? Project name (machine name) wp2syslog
? Repository clone URL 
? Ruby version 2.3.0
? Select plugins WordPress, Puppet
? Select a version of WordPress 4.8
? Does it use WP Starter (composer)? No
? Does it use the WP-CFM plugin? No
? Theme name (machine name) wp2syslog
? Install a fresh copy of WordPress? No
? Which host will it be deployed to? F1
? What is the path to the virtual host? /vagrant/public
? Does this project need a database? Yes
? What is the name of the database? web
? What is the user connecting to the database? web
? Which version of PHP to use? 5.6
? Does it use Solr? No
events.js:160
      throw er; // Unhandled 'error' event
      ^

TypeError: /usr/local/lib/node_modules/generator-web-starter/node_modules/generator-web-starter-wordpress/web-starter/templates/config/shell/custom/post-provision.unprivileged.sh:9
    7| 
    8| VAGRANT_CORE_FOLDER="/vagrant"
 >> 9| DOCROOT="/vagrant/<%= services.web.doc_root %>"
    10| 
    11| if [[ -f "${DOCROOT}/wp-config.vm.php" ]]; then
    12|   if [[ ! -f "${DOCROOT}/wp-config.php" || -w "${DOCROOT}/wp-config.php" ]]; then

Cannot read property 'doc_root' of undefined
    at eval (eval at compile (/usr/local/lib/node_modules/generator-web-starter/node_modules/ejs/lib/ejs.js:618:12), <anonymous>:11:38)
    at returnedFn (/usr/local/lib/node_modules/generator-web-starter/node_modules/ejs/lib/ejs.js:653:17)
    at Object.exports.render (/usr/local/lib/node_modules/generator-web-starter/node_modules/ejs/lib/ejs.js:416:37)
    at process (/usr/local/lib/node_modules/generator-web-starter/node_modules/mem-fs-editor/lib/actions/copy-tpl.js:12:18)
    at applyProcessingFunc (/usr/local/lib/node_modules/generator-web-starter/node_modules/mem-fs-editor/lib/actions/copy.js:13:16)
    at EditionInterface.exports._copySingle (/usr/local/lib/node_modules/generator-web-starter/node_modules/mem-fs-editor/lib/actions/copy.js:51:16)
    at EditionInterface.exports.copy (/usr/local/lib/node_modules/generator-web-starter/node_modules/mem-fs-editor/lib/actions/copy.js:23:17)
    at EditionInterface.module.exports [as copyTpl] (/usr/local/lib/node_modules/generator-web-starter/node_modules/mem-fs-editor/lib/actions/copy-tpl.js:10:8)
    at child.post_provision (/usr/local/lib/node_modules/generator-web-starter/node_modules/generator-web-starter-wordpress/web-starter/index.js:202:15)
    at Object.<anonymous> (/usr/local/lib/node_modules/generator-web-starter/node_modules/yeoman-generator/lib/base.js:431:23)
    at /usr/local/lib/node_modules/generator-web-starter/node_modules/run-async/index.js:25:25
    at /usr/local/lib/node_modules/generator-web-starter/node_modules/run-async/index.js:24:19
    at /usr/local/lib/node_modules/generator-web-starter/node_modules/yeoman-generator/lib/base.js:432:9
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
```

**Comment by johnbburg** [comment]
I may still not be using a fully updated generator, it didn't give me the option for PHP 7 when I ran it.

**Comment by johnbburg** [comment]
So I deleted all the generated files in my project root and re-ran the generator, It worked fine, also gave me the option for PHP 7.
