### ISSUE TITLE
solr is not defined

### ISSUE THREAD

**Issue by sejancich** [forumone/generator-web-starter#45]
When running the generator for Drupal 8, I'm getting an error about Solr being undefined.

```
sjancich-mac:drupal8 sjancich$ yo web-starter
? Project name (machine name) drupal8
? Repository clone URL 
? Select plugins Drupal
? Version 1.1.x
? Select a version of Drupal 8.1.0
? Does it use the Features module? No
? Does it use the Configuration module? No
? Theme name (machine name) 
? Install a fresh copy of Drupal? Yes
     info ... Fetching https://github.com/forumone/web-starter/archive/1.1.x.tar.gz ...
     info This might take a few moments
.✔ Done in /Users/sjancich/.cache/yeoman/forumone/web-starter/1.1.x
(!) #expand() is deprecated. Use the glob module.
(!) #expandFiles() is deprecated. Use the glob module.
(!) #expand() is deprecated. Use the glob module.
writing:aliases
writing:make
events.js:141
      throw er; // Unhandled 'error' event
      ^

ReferenceError: /Users/sjancich/Sites/drupal8/node_modules/generator-web-starter/node_modules/generator-web-starter-drupal/web-starter/templates/public/sites/default/settings.vm.php:568
    566| // $conf['allow_authorize_operations'] = FALSE;
    567| 
 >> 568| <% if (solr) { %>
    569| /**
    570|  * Solr Search API overrides
    571|  *

solr is not defined
    at eval (eval at <anonymous> (/Users/sjancich/Sites/drupal8/node_modules/generator-web-starter/node_modules/yeoman-generator/node_modules/mem-fs-editor/node_modules/ejs/lib/ejs.js:485:12), <anonymous>:11:12)
    at returnedFn (/Users/sjancich/Sites/drupal8/node_modules/generator-web-starter/node_modules/yeoman-generator/node_modules/mem-fs-editor/node_modules/ejs/lib/ejs.js:514:17)
    at Object.exports.render (/Users/sjancich/Sites/drupal8/node_modules/generator-web-starter/node_modules/yeoman-generator/node_modules/mem-fs-editor/node_modules/ejs/lib/ejs.js:316:37)
    at copy.process (/Users/sjancich/Sites/drupal8/node_modules/generator-web-starter/node_modules/yeoman-generator/node_modules/mem-fs-editor/lib/actions/copy-tpl.js:14:18)
    at applyProcessingFunc (/Users/sjancich/Sites/drupal8/node_modules/generator-web-starter/node_modules/yeoman-generator/node_modules/mem-fs-editor/lib/actions/copy.js:13:16)
    at EditionInterface.exports._copySingle (/Users/sjancich/Sites/drupal8/node_modules/generator-web-starter/node_modules/yeoman-generator/node_modules/mem-fs-editor/lib/actions/copy.js:51:16)
    at EditionInterface.exports.copy (/Users/sjancich/Sites/drupal8/node_modules/generator-web-starter/node_modules/yeoman-generator/node_modules/mem-fs-editor/lib/actions/copy.js:23:17)
    at EditionInterface.module.exports [as copyTpl] (/Users/sjancich/Sites/drupal8/node_modules/generator-web-starter/node_modules/yeoman-generator/node_modules/mem-fs-editor/lib/actions/copy-tpl.js:12:8)
    at module.exports.generators.Base.extend.writing.settings (/Users/sjancich/Sites/drupal8/node_modules/generator-web-starter/node_modules/generator-web-starter-drupal/web-starter/index.js:197:15)
    at /Users/sjancich/Sites/drupal8/node_modules/generator-web-starter/node_modules/yeoman-generator/lib/base.js:429:16
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

**Comment by tla-dev** [comment]
yes, I fixed it already but it hasn't been tagged so you still have the error
maybe you can download the source and do a npm link or ask for a tag
