### ISSUE TITLE
Gesso failing to install

### ISSUE THREAD

**Issue by mortona42** [forumone/generator-web-starter#57]
writing:aliases
writing:make
     info ... Fetching https://github.com/forumone/gesso-theme-libsass-drupal7/archive/master.tar.gz ...
     info This might take a few moments

events.js:160
      throw er; // Unhandled 'error' event
      ^
 HTTPError: Response code 404 (Not Found)
    at EventEmitter.<anonymous> (C:\Users\Andrew\AppData\Roaming\npm\node_modules\generator-web-starter\node_modules\got\index.js:192:24)
    at emitOne (events.js:96:13)
    at EventEmitter.emit (events.js:188:7)
    at Immediate._onImmediate (C:\Users\Andrew\AppData\Roaming\npm\node_modules\generator-web-starter\node_modules\got\index.js:58:8)
    at tryOnImmediate (timers.js:543:15)

**Comment by fafnirical** [comment]
This occurs in the following case:
* User has selected "drupal" for the platform; and
* User has selected to install a fresh copy of gesso

See https://github.com/forumone/generator-web-starter-gesso/blob/master/web-starter/index.js#L228-L231 -- the repository [forumone/gesso-theme-libsass-drupal7](https://github.com/forumone/gesso-theme-libsass-drupal7) no longer exists, and it should instead download [Gesso 7.x-2.0](https://www.drupal.org/project/gesso/releases/7.x-2.0) via Drupal.org.

The workaround for now is to not select the option to install Gesso, and instead install it manually.

**Comment by fafnirical** [comment]
Will be resolved by #59.
