### ISSUE TITLE
Drupal generator is broken

### ISSUE THREAD

**Issue by mortona42** [forumone/generator-web-starter#64]
TypeError: Cannot read property 'type' of undefined
    at /usr/local/lib/node_modules/yo/node_modules/yeoman-environment/node_modules/inquirer/lib/objects/choices.js:16:12
    at Array.map (native)
    at new module.exports (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/node_modules/inquirer/lib/objects/choices.js:15:26)
    at Prompt.module.exports (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/node_modules/inquirer/lib/prompts/base.js:43:24)
    at new Prompt (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/node_modules/inquirer/lib/prompts/list.js:26:8)
    at PromptUI.fetchAnswer (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/node_modules/inquirer/lib/ui/prompt.js:77:16)
    at tryCatcher (/usr/local/lib/node_modules/yo/node_modules/rx/dist/rx.js:63:31)
    at InnerObserver.Rx.FlatMapObservable.InnerObserver.next (/usr/local/lib/node_modules/yo/node_modules/rx/dist/rx.js:2140:43)
    at InnerObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/usr/local/lib/node_modules/yo/node_modules/rx/dist/rx.js:1762:31)
    at InnerObserver.tryCatcher (/usr/local/lib/node_modules/yo/node_modules/rx/dist/rx.js:63:31)
    at AutoDetachObserverPrototype.next (/usr/local/lib/node_modules/yo/node_modules/rx/dist/rx.js:5883:51)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/usr/local/lib/node_modules/yo/node_modules/rx/dist/rx.js:1762:31)
    at InnerObserver.next (/usr/local/lib/node_modules/yo/node_modules/rx/dist/rx.js:3547:65)
    at InnerObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/usr/local/lib/node_modules/yo/node_modules/rx/dist/rx.js:1762:31)
    at InnerObserver.tryCatcher (/usr/local/lib/node_modules/yo/node_modules/rx/dist/rx.js:63:31)
    at AutoDetachObserverPrototype.next (/usr/local/lib/node_modules/yo/node_modules/rx/dist/rx.js:5883:51)
events.js:160
      throw er; // Unhandled 'error' event
      ^

**Comment by tla-dev** [comment]
there shouldn't be quote here: https://github.com/forumone/generator-web-starter-drupal/blob/master/web-starter/index.js#L34

version_major : 7

I made a pull-request here: https://github.com/forumone/generator-web-starter-drupal/pull/6
