### ISSUE TITLE
Drupal generator is broken

### ISSUE THREAD

**Issue by mortona42** [forumone/generator-web-starter#70]
Selecting Drupal in yeoman leads to a crash:

```
readline.js:953
            throw err;
            ^

TypeError: Cannot read property 'value' of undefined
    at Prompt.getCurrentValue (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/node_modules/inquirer/lib/prompts/list.js:123:51)
    at tryCatcher (/usr/local/lib/node_modules/yo/node_modules/rx/dist/rx.js:63:31)
    at InnerObserver.next (/usr/local/lib/node_modules/yo/node_modules/rx/dist/rx.js:5407:43)
    at InnerObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/usr/local/lib/node_modules/yo/node_modules/rx/dist/rx.js:1762:31)
    at InnerObserver.tryCatcher (/usr/local/lib/node_modules/yo/node_modules/rx/dist/rx.js:63:31)
    at AutoDetachObserverPrototype.next (/usr/local/lib/node_modules/yo/node_modules/rx/dist/rx.js:5883:51)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/usr/local/lib/node_modules/yo/node_modules/rx/dist/rx.js:1762:31)
    at TakeObserver.next (/usr/local/lib/node_modules/yo/node_modules/rx/dist/rx.js:5646:17)
    at TakeObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/usr/local/lib/node_modules/yo/node_modules/rx/dist/rx.js:1762:31)
    at TakeObserver.tryCatcher (/usr/local/lib/node_modules/yo/node_modules/rx/dist/rx.js:63:31)
    at AutoDetachObserverPrototype.next (/usr/local/lib/node_modules/yo/node_modules/rx/dist/rx.js:5883:51)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/usr/local/lib/node_modules/yo/node_modules/rx/dist/rx.js:1762:31)
    at Subject.Rx.Subject.addProperties.onNext (/usr/local/lib/node_modules/yo/node_modules/rx/dist/rx.js:5998:19)
    at Subject.tryCatcher (/usr/local/lib/node_modules/yo/node_modules/rx/dist/rx.js:63:31)
    at AutoDetachObserverPrototype.next (/usr/local/lib/node_modules/yo/node_modules/rx/dist/rx.js:5883:51)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/usr/local/lib/node_modules/yo/node_modules/rx/dist/rx.js:1762:31)
    at AutoDetachObserver.tryCatcher (/usr/local/lib/node_modules/yo/node_modules/rx/dist/rx.js:63:31)
    at AutoDetachObserverPrototype.next (/usr/local/lib/node_modules/yo/node_modules/rx/dist/rx.js:5883:51)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/usr/local/lib/node_modules/yo/node_modules/rx/dist/rx.js:1762:31)
    at Interface.handler (/usr/local/lib/node_modules/yo/node_modules/rx/dist/rx.async.js:482:11)
    at emitOne (events.js:96:13)
    at Interface.emit (events.js:188:7)

```

**Comment by wwhurley** [comment]
Which version of the generator do you have?

**Comment by mortona42** [comment]
generator-web-starter@0.5.5

I did a [sudo npm update -g] before running, which I think should bring me up to the latest.

**Comment by TrevorScheitrum** [comment]
In trying to diagnose this with Andrew I found out that the selection arrow for the 'default' version of drupal is selecting the actual prompt text, not a possible choice.  So if you're mindlessly hitting 'enter' through all the prompts it will crash causing the error Andrew found.
![screenshot from 2016-09-08 10 40 55](https://cloud.githubusercontent.com/assets/1857060/18360050/5322df28-75b1-11e6-8e56-9cee0f8da598.png)
![screenshot from 2016-09-08 10 41 51](https://cloud.githubusercontent.com/assets/1857060/18360051/5325b658-75b1-11e6-9c16-6d380635e925.png)

**Comment by mortona42** [comment]
I'm not sure how you got those additional options, but this is what I'm seeing:
![screen shot 2016-09-08 at 10 43 07 am](https://cloud.githubusercontent.com/assets/696005/18360080/76ccd064-75b1-11e6-90d0-26de46b79c7a.png)
![screen shot 2016-09-08 at 10 44 10 am](https://cloud.githubusercontent.com/assets/696005/18360077/74164508-75b1-11e6-97d0-88c80c82e15f.png)

My mistake was assuming the only option would be selected by default.  Any way to make a selection required?

**Comment by dcmouyard** [comment]
I’m also getting an error when trying to install Drupal 8 for a new project.

```
$ yo web-starter
? Project name (machine name) eight
? Repository clone URL 
? Ruby version 2.3.0
? Select plugins Drupal 8, Gesso, Capistrano, Grunt, Puppet
? Select a version of Drupal 8.1.9
? Does it use the Features module? No
? Theme name (machine name) test_theme
? Install a fresh copy of Drupal? Yes
? Install a fresh copy of the gesso theme? Yes
? Does this project use Sass? Yes
? Sass compilation Libsass
? Does this project use Pattern Lab? Yes
? Install a fresh copy of Pattern Lab? Yes
? Method of deploying code git
? Number of releases to keep 3
? Which host will it be deployed to? F1
? What is the path to the virtual host? /vagrant/public
? Does this project need a database? Yes
? What is the name of the database? web
? What is the user connecting to the database? web
? Which version of PHP to use? 5.6
? Does it use Solr? Yes

events.js:141
      throw er; // Unhandled 'error' event
      ^
AssertionError: Trying to copy from a source that does not exist: /Users/dmouyard/projects/generator-web-starter/node_modules/generator-web-starter-puppet/web-starter/templates/puppet/manifests/hieradata/platforms/drupal8.yaml
    at EditionInterface.exports._copySingle (/Users/dmouyard/projects/generator-web-starter/node_modules/mem-fs-editor/lib/actions/copy.js:45:3)
    at EditionInterface.exports.copy (/Users/dmouyard/projects/generator-web-starter/node_modules/mem-fs-editor/lib/actions/copy.js:23:17)
    at EditionInterface.module.exports [as copyTpl] (/Users/dmouyard/projects/generator-web-starter/node_modules/mem-fs-editor/lib/actions/copy-tpl.js:10:8)
    at module.exports.generators.Base.extend.writing.init (/Users/dmouyard/projects/generator-web-starter/node_modules/generator-web-starter-puppet/web-starter/index.js:140:15)
    at Object.<anonymous> (/Users/dmouyard/projects/generator-web-starter/node_modules/yeoman-generator/lib/base.js:431:23)
    at /Users/dmouyard/projects/generator-web-starter/node_modules/run-async/index.js:26:25
    at /Users/dmouyard/projects/generator-web-starter/node_modules/run-async/index.js:25:19
    at /Users/dmouyard/projects/generator-web-starter/node_modules/yeoman-generator/lib/base.js:432:9
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

I’m using
* node v4.4.1
* npm 2.14.20
* latest master branch of generator-web-starter

**Comment by wwhurley** [comment]
How did you install the generator? Was it using npm install or did you clone it?

**Comment by mortona42** [comment]
In the past I cloned it, but I removed those and installed via npm.  Today I uninstalled yeoman, generator-web-starter and reinstalled.

**Comment by wwhurley** [comment]
That last question for for @dcmouyard. I understand @TrevorScheitrum was able to narrow it down to a required element not having a value and actually being -- you know -- required in the UI. Is that fair to say?

**Comment by dcmouyard** [comment]
I had cloned it, like it says in README.md

**Comment by wwhurley** [comment]
Ahhh... yeah. So we should fix that, @dcmouyard. We have proper releases now so it should be done via `npm install generator-web-starter -g` -- you may need to run this with elevated permissions.

**Comment by dcmouyard** [comment]
Ok, so it works now for D7, but no option for D8

**Comment by wwhurley** [comment]
Correct. The D8 change is part of the 0.6 version which is currently in progress. We expect to release that in the next week. What are you trying to set up?

**Comment by dcmouyard** [comment]
I just wanted a vanilla install of Drupal 8 up & running for testing Gesso and the Pattern Lab Twig Starterkit.

I can wait until the 0.6 version is out next week.

**Comment by mortona42** [comment]
Yup, solved it for me.

**Comment by johnbburg** [comment]
I'm getting a similar error, albeit with a different stack trace:

```
$ yo web-starter
? Project name (machine name) my-project
? Repository clone URL git@github.com:my-project/public-site-d7.git
? Ruby version 2.3.0
? Select plugins Drupal 7, Capistrano, Grunt, Puppet
? Version 1.1.x
events.js:160
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read property 'nodeValue' of undefined
    at /home/jbrandenburg/Projects/my-project/node_modules/generator-web-starter/node_modules/generator-web-starter-drupal/node_modules/drupal-modules/index.js:24:54
    at /home/jbrandenburg/Projects/my-project/node_modules/generator-web-starter/node_modules/lodash/lodash.js:935:11
    at /home/jbrandenburg/Projects/my-project/node_modules/generator-web-starter/node_modules/lodash/lodash.js:4920:15
    at baseReduce (/home/jbrandenburg/Projects/my-project/node_modules/generator-web-starter/node_modules/lodash/lodash.js:932:5)
    at Function.reduce (/home/jbrandenburg/Projects/my-project/node_modules/generator-web-starter/node_modules/lodash/lodash.js:9698:14)
    at /home/jbrandenburg/Projects/my-project/node_modules/generator-web-starter/node_modules/generator-web-starter-drupal/node_modules/drupal-modules/index.js:22:21
    at tryCatcher (/home/jbrandenburg/Projects/my-project/node_modules/generator-web-starter/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/jbrandenburg/Projects/my-project/node_modules/generator-web-starter/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/home/jbrandenburg/Projects/my-project/node_modules/generator-web-starter/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/home/jbrandenburg/Projects/my-project/node_modules/generator-web-starter/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/home/jbrandenburg/Projects/my-project/node_modules/generator-web-starter/node_modules/bluebird/js/release/promise.js:691:18)
    at Promise._fulfill (/home/jbrandenburg/Projects/my-project/node_modules/generator-web-starter/node_modules/bluebird/js/release/promise.js:636:18)
    at Object.done (/home/jbrandenburg/Projects/my-project/node_modules/generator-web-starter/node_modules/bluebird/js/release/nodeback.js:42:21)
    at process.nextTick (/home/jbrandenburg/Projects/my-project/node_modules/generator-web-starter/node_modules/generator-web-starter-drupal/node_modules/drupal-modules/node_modules/jsdom/lib/jsdom.js:320:18)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

npm 4.2.0
yo 1.8.5
generator-web-starter 0.6.0
